=== matthewg/Zevils/net-oscar/lib/Net/OSCAR/Protocol.dtd
<!ELEMENT oscar (define)+>

<!ELEMENT define (ref|byte|word|dword|data|tlvchain|if)+>
<!ATTLIST define
	name ID #REQUIRED
	channel CDATA #IMPLIED
	family CDATA #IMPLIED
	subtype CDATA #IMPLIED
>

<!ELEMENT ref (EMPTY)>
<!ATTLIST ref
	name IDREF #REQUIRED
>

<!ELEMENT byte (#PCDATA)>
<!ATTLIST byte
	name CDATA #IMPLIED
>
<!ELEMENT word (#PCDATA)>
<!ATTLIST word
	name CDATA #IMPLIED
	order (network|vax) #DEFAULT network
>
<!ELEMENT dword (#PCDATA)>
<!ATTLIST dword
	name CDATA #IMPLIED
	order (network|vax) #DEFAULT network
>
<!ELEMENT data (#PCDATA)>
<!ATTLIST data
	name CDATA #IMPLIED
	order (network|vax) #DEFAULT network
	length_prefix (byte|word|dword) #IMPLIED
>

<!ELEMENT tlvchain (tlv*)>
<!ATTLIST tlvchain
	name CDATA #IMPLIED
	short (yes|no) #DEFAULT no <!-- A 'short' TLV is type/num/length/value, where num and length are both bytes.  It's used in extended status. -->
	count_prefix (byte|word|dword) #IMPLIED
	length_prefix (byte|word|dword) #IMPLIED
>

<!ELEMENT tlv (ref|byte|word|dword|data|tlvchain|if)+>
<!ATTLIST tlv
	name CDATA #IMPLIED
	num CDATA #REQUIRED
	num2 CDATA #IMPLIED
>

<!ELEMENT if (condition+)>
<!ELEMENT condition (ref|byte|word|dword|data|tlvchain|if)+>
<!ATTLIST condition
	test CDATA #REQUIRED
>

=== matthewg/Zevils/net-oscar/OSCAR/Protocol.xml
<?xml version="1.0"?>
<!DOCTYPE greeter SYSTEM "Protocol.dtd">

<oscar>
	<define name="flap">
		<byte>0x2A</byte> <!-- FLAP packet start indicator -->
		<byte name="channel">FLAP_CHAN_SNAC</byte>
		<word name="seqno" />
		<data length_prefix="word" name="msg" />
	</define>

	<define name="snac">
		<word name="family" />
		<word name="subtype" />
		<word name="flags" />
		<dword name="reqid" />
		<data name="data" />
	</define>

	<define name="userinfo">
		<data name="screenname" length_prefix="byte" />
		<word name="evil" />
		<tlvchain count_prefix="word">
			<tlv name="flags" type="1"><word /></tlv>
			<tlv name="membersince" type="2"><dword /></tlv>
			<tlv name="onsince" type="3"><dword /></tlv>
			<tlv name="idle" type="4"><word /></tlv>
			<tlv name="capabilities" type="13"><data length="16" count="-1" /></tlv>
			<tlv type="29">
				<tlvchain short="yes">
					<tlv name="icon_md5sum" type="1" shortno="1"><data /></tlv>
					<tlv name="extended_status" type="2"><data length_prefix="word" /></tlv>
				</tlvchain>
			</tlv>
		</tlvchain>
		<tlvchain>
			<tlv name="profile" type="2"><data /></tlv>
			<tlv name="awaymsg" type="4"><data /></tlv>
			<tlv name="chatdata" type="5"><data /></tlv>
		</tlvchain>
	</define>
</oscar>

=== matthewg/Zevils/net-oscar/t/test.xml
<?xml version="1.0"?>
<!DOCTYPE oscar SYSTEM "Protocol.dtd">

<oscar>
	<!-- Simple primitives -->
	<define name="just_byte"><byte /></define>
	<define name="just_word"><word /></define>
	<define name="just_dword"><dword /></define>
	<define name="just_data"><data /></define>

	<!-- Naming -->
	<define name="named_element"><data name="foo" /></define>

	<!-- Fixed values -->
	<define name="fixed_value"><word>123</word></define>

	<!-- Length prefixes, counts -->
	<define name="length_prefix"><data length_prefix="word" /></define>
	<define name="vax_prefix"><data length_prefix="word" prefix_order="vax" /></define>
	<define name="count_prefix"><data count_prefix="word" /></define>
	<define name="repeated_data"><data count="-1" /></define>
	<define name="fixed_width_data"><data length="10" /></define>

	<!-- TLVs -->
	<define name="basic_tlv">
		<tlvchain>
			<tlv type="1"><data /></tlv>
			<tlv type="2"><data /></tlv>
		</tlvchain>
	</define>
	<define name="named_tlv">
		<tlvchain>
			<tlv type="1" name="foo"><data /></tlv>
			<tlv type="2" name="bar"><data /></tlv>
		</tlvchain>
	</define>
	<define name="complex_data_tlv">
		<tlvchain>
			<tlv type="1">
				<data name="foo" />
				<word name="bar" />
				<dword />
				<byte name="baz" />
			</tlv>
		</tlvchain>
	</define>
	<define name="subtyped_tlv">
		<tlvchain subtyped="yes">
			<tlv type="1" subtype="1" name="foo"><data /></tlv>
			<tlv type="1" subtype="2" name="bar"><data /></tlv>
		</tlvchain>
	</define>
	<define name="count_prefic_tlv">
		<tlvchain count_prefix="word">
			<tlv type="1"><data /></tlv>
		</tlvchain>
	</define>

	<!-- ref -->
	<define name="ref_foo"><data /></define>
	<define name="ref_bar"><data /></define>
	<define name="ref"><ref name="ref_foo" /><ref name="ref_bar" /></define>

	<!-- SNAC -->
	<define name="snac" family="1" subtype="2"><data /></define>

	<!-- Miscellaneous -->
	<define name="empty_def" />

</oscar>

=== matthewg/Zevils/net-oscar/lib/Net/OSCAR/Protocol.xml
<?xml version="1.0"?>
<!DOCTYPE greeter SYSTEM "Protocol.dtd">

<oscar>
	<define name="flap">
		<byte>42</byte> <!-- FLAP packet start indicator -->
		<byte name="channel">2</byte>
		<word name="seqno" />
		<data length_prefix="word" name="msg" />
	</define>

	<define name="snac">
		<word name="family" />
		<word name="subtype" />
		<word name="flags" />
		<dword name="reqid" />
		<data name="data" />
	</define>

	<define name="get info" family="2" subtype="21">
		<word>0</word>
		<word>1</word>
		<data length_prefix="byte" name="screenname" />
	</define>
	<define name="get away" family="2" subtype="21">
		<word>0</word>
		<word>3</word>
		<data length_prefix="byte" name="screenname" />
	</define>

	<define name="signon_TLV">
		<tlvchain>
			<tlv type="1"><data name="screenname" /></tlv>
			<tlv type="3"><data name="clistr" /></tlv>
			<tlv type="22"><word name="supermajor" /></tlv>
			<tlv type="23"><word name="major" /></tlv>
			<tlv type="24"><word name="minor" /></tlv>
			<tlv type="25"><word name="subminor" /></tlv>
			<tlv type="26"><word name="build" /></tlv>
			<tlv type="20"><dword name="subbuild" /></tlv>
			<tlv type="15"><data>en</data></tlv>
			<tlv type="14"><data>us</data></tlv>
			<tlv type="74"><byte>1</byte></tlv>
		</tlvchain>
	</define>
	<define name="signon" family="23" subtype="2">
		<ref name="signon_TLV" />
		<tlvchain>
			<tlv type="37"><data name="auth_response" /></tlv>
			<tlv type="76"><data name="betainfo" /></tlv>
		</tlvchain>
	</define>
	<define name="signon_ICQ" family="23" subtype="2">
		<ref name="signon_TLV" />
		<tlvchain>
			<tlv type="2"><data name="password" /></tlv>
		</tlvchain>
	</define>

	<define name="userinfo">
		<data name="screenname" length_prefix="byte" />
		<word name="evil" />
		<tlvchain count_prefix="word">
			<tlv name="flags" type="1"><word /></tlv>
			<tlv name="membersince" type="2"><dword /></tlv>
			<tlv name="onsince" type="3"><dword /></tlv>
			<tlv name="idle" type="4"><word /></tlv>
			<tlv name="capabilities" type="13"><data length="16" count="-1" /></tlv>
			<tlv type="29">
				<tlvchain short="yes">
					<tlv type="1" shortno="1"><data name="icon_md5sum" /></tlv>
					<tlv type="2"><data length_prefix="word" name="extended_status" /></tlv>
				</tlvchain>
			</tlv>
		</tlvchain>
		<tlvchain>
			<tlv type="2"><data name="profile" /></tlv>
			<tlv type="4"><data name="awaymsg" /></tlv>
			<tlv type="5"><data name="chatdata" /></tlv>
		</tlvchain>
	</define>
</oscar>
